---
title: "Leading Causes of Death in the U.S."
author: "Tanner Gildea"
date: "7/17/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.width = 8, 
                      fig.height = 5)

library(tidyverse)
library(readxl)
library(ggplot2)
library(ggthemes)
library(scales)
library(maps)

NCHS <- read.csv("NCHS.csv") %>% 
  select(-X113.Cause.Name)  
  
```

```{r top_two_totals}

# Projected nationwide trends of all 10 (or 5?)

trends_top_two <- NCHS %>% 
  select(Year, Cause.Name, Deaths) %>% 
  group_by(Year, Cause.Name) %>% 
  summarize("Deaths" = sum(Deaths)) %>% 
  filter(Cause.Name != "All causes") %>% 
  na.omit() %>% 
  filter(Cause.Name == "Cancer" | Cause.Name == "Heart disease")

ggplot(trends_top_two, aes(x = Year,
                   y = Deaths, 
                   color = Cause.Name,
                   fill = Cause.Name)) +
  
  geom_point(size = 1.5) +
  geom_smooth() +
  
  scale_y_continuous(labels = scales::comma) + 
  
  scale_fill_discrete(name = "Cause of Death") + 
  scale_color_discrete(name = "Cause of Death") +
  
  labs(x = NULL, y = "Total Number of Deaths Nationwide",
       title = "Top Two Leading Causes of Death in the United States, 1999-2016",
       subtitle = "Heart Disease and Cancer Most Deadly",
       caption = "Source: Center for Disease Control and Prevention") +
  
  theme_tufte() +
  
  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.subtitle = element_text(face = "italic"),
        legend.title = element_text(size = rel(1.2), face = "bold"),
        axis.title.y = element_text(size = rel(1.2)),
        plot.caption = element_text(face = "italic"),
        panel.grid.major.y = element_line(color = "gray"))

```

```{r top_eight_totals}

trends_bottom_eight <- NCHS %>% 
  select(Year, Cause.Name, Deaths) %>% 
  group_by(Year, Cause.Name) %>% 
  summarize("Deaths" = sum(Deaths)) %>% 
  filter(Cause.Name != "All causes") %>% 
  filter(Cause.Name != "Cancer") %>% 
  filter(Cause.Name != "Heart disease") %>% 
  na.omit() 

ggplot(trends_bottom_eight, aes(x = Year,
                   y = Deaths, 
                   color = Cause.Name,
                   fill = Cause.Name)) +
  
  geom_point(size = 1.5) +
  geom_smooth() +
    
  scale_y_continuous(labels = scales::comma,
                     breaks = c(100000, 150000, 200000, 250000, 300000)) + 
  
  labs(x = NULL, y = "Total Number of Deaths Nationwide",
       title = "Top Ten Killers in the United States Cont.",
       subtitle = "Stroke, Chronic Lower Respiratory Disease, and Unintentional Injuries Round Out the Top Five",
       caption = "Source: Center for Disease Control and Prevention") +
  
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +
  
  scale_fill_discrete(name = "Cause of Death") + 
  scale_color_discrete(name = "Cause of Death") +
  
  theme_tufte() +
  
  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.subtitle = element_text(face = "italic"),
        legend.title = element_text(size = rel(1.2), face = "bold"),
        axis.title.y = element_text(size = rel(1.2)),
        plot.caption = element_text(face = "italic"),
        panel.grid.major.y = element_line(color = "gray"))


```



```{r death_props_two}

death_rate <- NCHS %>% 
  group_by(Year, Cause.Name) %>% 
  summarize(Age.adjusted.Death.Rate = mean(Age.adjusted.Death.Rate)) %>% 
  filter(Cause.Name != "All causes") %>%
  filter(Cause.Name == "Cancer" | Cause.Name == "Heart disease") %>% 
  na.omit() 

ggplot(death_rate, aes(x = Year,
                       y = Age.adjusted.Death.Rate,
                       color = Cause.Name,
                       fill = Cause.Name)) +

  geom_point(size = 1.5) +
  geom_smooth() +

  scale_fill_discrete(name = "Cause of Death") +
  scale_color_discrete(name = "Cause of Death") +

  labs(x = NULL, y = "Mean Age-adjusted Death Rate",
       title = "Cancer and Heart Disease Death Rates Trending Downwards",
       subtitle = "Deaths per 100,000",
       caption = "Source: Center for Disease Control and Prevention") +

  theme_tufte() +

  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.subtitle = element_text(face = "italic"),
        legend.title = element_text(size = rel(1.2), face = "bold"),
        axis.title.y = element_text(size = rel(1.2)),
        plot.caption = element_text(face = "italic"),
        panel.grid.major.y = element_line(color = "gray"),
        panel.grid.minor.y = element_line(color = "gray"))


```

```{r death_props_eight}

death_rate <- NCHS %>% 
  group_by(Year, Cause.Name) %>% 
  summarize(Age.adjusted.Death.Rate = mean(Age.adjusted.Death.Rate)) %>% 
  filter(Cause.Name != "All causes") %>% 
  filter(Cause.Name != "Cancer") %>% 
  filter(Cause.Name != "Heart disease") %>% 
  na.omit() 

ggplot(death_rate, aes(x = Year,
                       y = Age.adjusted.Death.Rate,
                       color = Cause.Name,
                       fill = Cause.Name)) +

  geom_point(size = 1.5) +
  geom_smooth() +

  scale_fill_discrete(name = "Cause of Death") +
  scale_color_discrete(name = "Cause of Death") +
  
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +

  labs(x = NULL, y = "Mean Age-adjusted Death Rate",
       title = "Death Rates for Other Top Killers",
       subtitle = "Trends are mixed: Strokes are down, Alzheimer's on the rise",
       caption = "Source: Center for Disease Control and Prevention") +

  theme_tufte() +

  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.subtitle = element_text(face = "italic"),
        legend.title = element_text(size = rel(1.2), face = "bold"),
        axis.title.y = element_text(size = rel(1.2)),
        plot.caption = element_text(face = "italic"),
        panel.grid.major.y = element_line(color = "gray"))


```

```{r map_data_prep}
# Map with shading according to number 1 killer in past 5 years
us_states <- map_data("state")

NCHS_states <- NCHS 
NCHS_states$region <- tolower(NCHS_states$State)

NCHS_states_joined <- left_join(us_states, NCHS_states)

```

```{r map_heart_disease}

heart_disease <- NCHS_states_joined %>% 
  filter(Cause.Name == "Heart disease") %>% 
  filter(Year %in% c(2013,2014,2015,2016))

ggplot(data = heart_disease, aes(x = long,
                             y = lat,
                             group = group,
                             fill = Age.adjusted.Death.Rate)) +
  
  facet_wrap(~Year, ncol = 2) +

  geom_polygon(color = "grey90", size = .1) +

  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +   # curves map to annoy flat-earthers
  
  labs(x = NULL, y = NULL,
       title = "Heart Disease Death Rates By State",
       subtitle = NULL,
       caption = "Source: Center for Disease Control and Prevention",
       fill = "Death rate per 100,000 persons") +
  
  scale_fill_viridis_c(option = "inferno") +
  
  theme_map() +
  
  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.caption = element_text(face="italic"),
        legend.position = "bottom",
        strip.background = element_blank())
```

```{r map_suicide}

suicide <- NCHS_states_joined %>% 
  filter(Cause.Name == "Suicide") %>% 
  filter(Year %in% c(2013,2014,2015,2016))

ggplot(data = suicide, aes(x = long,
                             y = lat,
                             group = group,
                             fill = Age.adjusted.Death.Rate)) +
  
  facet_wrap(~Year, ncol = 2) +

  geom_polygon(color = "grey90", size = .1) +

  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +   # curves map to annoy flat-earthers
  
  labs(x = NULL, y = NULL,
       title = "Suicide Death Rates By State",
       subtitle = NULL,
       caption = "Source: Center for Disease Control and Prevention",
       fill = "Death rate per 100,000 persons") +
  
  scale_fill_viridis_c(option = "cividis") +
  
  theme_map() +
  
  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.caption = element_text(face="italic"),
        legend.position = "bottom",
        strip.background = element_blank())

```


```{r map_influenza}
influenza <- NCHS_states_joined %>% 
  filter(Cause.Name == "Influenza and pneumonia") %>% 
  filter(Year %in% c(2013,2014,2015,2016))

ggplot(data = influenza, aes(x = long,
                             y = lat,
                             group = group,
                             fill = Age.adjusted.Death.Rate)) +
  
  facet_wrap(~Year, ncol = 2) +

  geom_polygon(color = "grey90", size = .1) +

  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +   # curves map to annoy flat-earthers
  
  labs(x = NULL, y = NULL,
       title = "Influenza and Pneumonia Death Rates By State",
       subtitle = NULL,
       caption = "Source: Center for Disease Control and Prevention",
       fill = "Death rate per 100,000 persons") +
  
  scale_fill_viridis_c(option = "viridis") +
  
  theme_map() +
  
  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.caption = element_text(face="italic"),
        legend.position = "bottom",
        strip.background = element_blank())

```

```{r map_unintentional}
unintentional <- NCHS_states_joined %>% 
  filter(Cause.Name == "Unintentional injuries") %>% 
  filter(Year %in% c(2013, 2014,2015,2016))

ggplot(data = unintentional, aes(x = long,
                             y = lat,
                             group = group,
                             fill = Age.adjusted.Death.Rate)) +
  
  facet_wrap(~Year, ncol = 2) +

  geom_polygon(color = "grey90", size = .1) +

  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +   # curves map to annoy flat-earthers
  
  labs(x = NULL, y = NULL,
       title = "Unintentional Death Rates By State",
       subtitle = NULL,
       caption = "Source: Center for Disease Control and Prevention",
       fill = "Death rate per 100,000 persons") +
  
  scale_fill_viridis_c(option = "plasma") +
  
  theme_map() +
  
  theme(plot.title = element_text(size = rel(1.5), face ="bold"),
        plot.caption = element_text(face="italic"),
        legend.position = "bottom",
        strip.background = element_blank())

```




